version: '3.7'
services:
  mysql:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'demo_security'
      MYSQL_USER: 'user_dev'
      MYSQL_PASSWORD: 'pazzword'
      MYSQL_ROOT_PASSWORD: 'pazzword'
      TZ: 'Asia/Ho_Chi_Minh'
    volumes:
      - ./mysql-volume:/var/lib/mysql
#      - ./mysql-conf/my.cnf:/etc/alternatives/my.cnf
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    expose:
      - '3307'
